/// Flutter icons SilverPathIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SilverPathIcons
///      fonts:
///       - asset: fonts/SilverPathIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SilverPathIcons {
  SilverPathIcons._();

  static const _kFontFam = 'SilverPathIcons';

  static const IconData thallain =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData seelie = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData unseelie =
      const IconData(0xe802, fontFamily: _kFontFam);
}
